name = "Miter"
uuid = "e2c39885-2134-4813-a274-cbd32ca8996e"
version = "0.17.1"
authors = ["Tam√°s K. Papp <tkpapp@gmail.com>"]

[workspace]
projects = ["test", "docs"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LaTeXEscapes = "cf6549fa-34fa-4b85-907d-0f184605242c"
Poppler_jll = "9c32591e-4766-534b-9725-b71a8799265b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
tectonic_jll = "d7dd28d6-a5e6-559c-9131-7eb760cdacc5"

[weakdeps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[extensions]
MiterStatsBaseExt = "StatsBase"

[compat]
Accessors = "0.1"
ArgCheck = "2"
Automa = "1"
Cairo = "1.1.1"
ColorTypes = "0.11, 0.12"
ConstructionBase = "1"
DocStringExtensions = "0.9"
LaTeXEscapes = "0.2.0"
Poppler_jll = "24.6.0"
Printf = "1.8"
Reexport = "1"
StaticArrays = "1"
Statistics = "1"
StatsBase = "0.34"
julia = "1.11"
tectonic_jll = "0.15.0"
